image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - apt-get install -y default-jre-headless locales
    - npm install -D typescript
    - npm install
    - mkdir -p output/static
  artifacts:
    paths:
      - node_modules/

testing_testing:
  stage: test
  script:
    - npm install -D typescript
    - npm test
